### ISSUE TITLE
How to monitoring internet connection in the same way?

### ISSUE THREAD

**Issue by e1jo** [CathalButler/openwrt-telegram-notifier#1]
For example i need message like this:

"wan interface is up, ip address is xxx:xxx:xxx:xxx"

**Comment by CathalButler** [comment]
[hostapd](https://w1.fi/hostapd/) does not have the support to monitor the wan interface.

You could use LuaSocket and LuCi Json packages with a script and set a cron job to run every minute that pings a remote server of your choice and then base the telegram notification around the result of the response.

Hope this helps!

**Comment by CathalButler** [comment]
Something like this would work as well:

```
#!/bin/sh

# Telegram bot settings
BOT_TOKEN="YOUR_BOT_TOKEN_HERE"
CHAT_ID="YOUR_CHAT_ID_HERE"

while true
do
    ping -c 1 google.com > /dev/null
    if [ $? -eq 0 ]
    then
        echo "Internet is up"
    else
        echo "Internet is down"
        curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            -d text="Warning! The internet connection is down!"
    fi
    sleep 60
done

```
